spring:
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

aws:
  s3:
    access-key: ENC(LdV8141/N8cy8v5rdxodwSneURe1S14pbSuWB7KeY34=)
    secret-key: ENC(6+gQntcb3Uj/DpwUm6SZidulEAYEh4CU9T/l2V5N7Bs9A72k1WVs8Wtinj0+GneE0S7r2a8K7Ng=)
    region: ENC(BfxHk2ztQaISSP9TaKHefsKUs/NcLEuh)
    bucket: ENC(/yFc8jUAwMA1xky9ZwbNFSDDXRP5zvakkM3SRr95bkE=)

server:
  port: 8080

jasypt:
  encryptor:
    password: commit
    poolSize: 2